path:
  root: ../../cadenza_data_demo/cad1/task1
  metadata_dir: ${path.root}/task1/metadata
  music_dir: ${path.root}/task1/audio/musdb18hq
  music_train_file: ${path.metadata_dir}/musdb18.train.json
  music_valid_file: ${path.metadata_dir}/musdb18.valid.json
  listeners_train_file: ${path.metadata_dir}/listeners.train.json
  listeners_valid_file: ${path.metadata_dir}/listeners.valid.json
  exp_folder: ./exp # folder to store enhanced signals and final results


sample_rate: 44100

nalr:
  nfir: 220
  sample_rate: ${sample_rate}

apply_compressor: False
compressor:
  threshold: 0.35
  attenuation: 0.1
  attack: 50    #35
  release: 750 #750
  rms_buffer_size: 0.064

compressor_vocals:
  threshold: 0.10 
  attenuation: 0.1
  attack: 50    #35
  release: 750 #750
  rms_buffer_size: 0.064

compressor_drums:
  threshold: 0.10 
  attenuation: 0.1
  attack: 50    #35
  release: 750 #750
  rms_buffer_size: 0.064 

compressor_bass:
  threshold: 0.10 
  attenuation: 0.1
  attack: 50    #35
  release: 750 #750
  rms_buffer_size: 0.064 

compressor_other:
  threshold: 0.25 
  attenuation: 0.1
  attack: 50    #35
  release: 750 #750
  rms_buffer_size: 0.064





soft_clip: True

separator:
  model: demucs   # demucs or openunmix
  sources: [drums, bass, other, vocals]
  device: ~

evaluate:
  set_random_seed: True
  small_test: False
  batch_size: 1  # Number of batches
  batch: 0       # Batch number to evaluate

# hydra config
hydra:
  run:
    dir: ${path.exp_folder}